### PR TITLE
Add ahash::AHashSet comparison to benchmark

### PR DESCRIPTION
**Pull request by Robbepop**
Timings on my machine upon `cargo run --release`:
```
build std::collections::HashSet: 5.79s
build rustc_hash::FxHashSet: 7.96s
build ahash::HashSet: 7.88s
lookup std::collections::HasSet: 8.61s
lookup rustc_hash::FxHashSet: 4.49s
lookup ahash::AHashSet: 4.45s
```
Link: https://docs.rs/ahash/0.7.0/ahash/

### CODE REVIEW

**Comment by matklad** [comment]
Timing seems of -- 

```
build std::collections::HashSet: 5.79s
lookup std::collections::HasSet: 8.61s
```

I suggest using https://github.com/amanusk/s-tui to check if you hit thermal thorottling. There are some buggy laptops that throttle at 80C, crippling down the perf of an otherwise excellent CPU

**Comment by matklad** [comment]
lol, timing is off on my machine as well, something's going on here...

**Comment by matklad** [comment]
https://users.rust-lang.org/t/building-hash-map-is-cheaper-than-doing-lookups/55044

**Comment by Robbepop** [comment]
> https://users.rust-lang.org/t/building-hash-map-is-cheaper-than-doing-lookups/55044

This indeed is interesting ...
I reran benchmarks on my system:
```
build std::collections::HashSet: 5.76s
build rustc_hash::FxHashSet: 7.72s
build ahash::HashSet: 7.77s
lookup std::collections::HasSet: 8.46s
lookup rustc_hash::FxHashSet: 3.92s
lookup ahash::AHashSet: 3.91s
```
Point is that `ahash` seems to be performing equally good under this simple benchmark as `rustc_hash` while stating to be DOS resistant. Well ... at least on my machine. :sweat_smile:

**Comment by matklad** [comment]
@Robbepop re-run the code from master, ther's a typo in your pr, the hm2 is used twice

**Comment by Robbepop** [comment]
> @Robbepop re-run the code from master, ther's a typo in your pr, the hm2 is used twice

oh my! thanks for telling ... :D

looks worse indeed.
```
build std::collections::HashSet: 5.72s
build rustc_hash::FxHashSet: 7.80s
build ahash::HashSet: 7.78s
lookup std::collections::HasSet: 8.35s
lookup rustc_hash::FxHashSet: 4.09s
lookup ahash::AHashSet: 4.68s
```

**Comment by Robbepop** [comment]
I just added
```toml
[profile.release]
lto = "fat"
codegen-units = 1
```
to the `Cargo.toml` which changes benchmark results completely:
```
build std::collections::HashSet: 7.19s
build rustc_hash::FxHashSet: 7.44s
build ahash::HashSet: 7.61s
lookup std::collections::HasSet: 6.26s
lookup rustc_hash::FxHashSet: 3.52s
lookup ahash::AHashSet: 3.69s
```
Maybe `std` components are inlined differently than custom dependencies.

**Comment by matklad** [comment]
oh wow (put std second just in case):

```
build rustc_hash::FxHashSet       1.95s
build std::collections::HashSet   3.50s
build ahash::HashSet              2.11s

lookup rustc_hash::FxHashSet      1.63s
lookup std::collections::HasSet   5.11s
lookup ahash::AHashSet            1.91s
```

Ive seen something similar in https://github.com/rust-lang/rust/issues/64075

**Comment by Robbepop** [comment]
Having the above mentioned `lto` and `codegen-units` set I do not see a difference when switchign the order.
```
build rustc_hash::FxHashSet: 7.43s
build std::collections::HashSet: 7.55s
build ahash::HashSet: 7.61s
lookup rustc_hash::FxHashSet: 3.53s
lookup std::collections::HasSet: 6.23s
lookup ahash::AHashSet: 3.62s
```

**Pull request merged**
